[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_prediction = "9bK6W6uAS2xC9Xdw6fcMgHH1BwLp4gJDKj5dwciF8CPe"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"
