// Detailed transaction test with error catching
require('dotenv').config();
const { ethers } = require('ethers');

const ARC_RPC = "https://rpc.testnet.arc.network";
const CONTRACT_ADDRESS = "0x4AD92eAFb8867f4d5c95dcB7eDc922E30B3bc1C8";
const PRIVATE_KEY = process.env.PRIVATE_KEY;

const ABI = [
    "function placeBet(uint256 _betId, uint8 _direction, uint256 _duration, uint256 _entryPrice, uint8 _marketId, address _payoutAddress) external payable",
    "function bets(uint256) view returns (uint256 id, address user, uint256 amount, uint8 direction, uint256 entryPrice, uint256 timestamp, uint256 duration, uint8 marketId, uint256 settlementPrice, bool settled, bool won)"
];

async function detailedTest() {
    console.log("🔍 Detailed Transaction Test\n");

    const provider = new ethers.JsonRpcProvider(ARC_RPC);
    const wallet = new ethers.Wallet(PRIVATE_KEY, provider);
    const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, wallet);

    // Check balances
    const walletBal = await provider.getBalance(wallet.address);
    const contractBal = await provider.getBalance(CONTRACT_ADDRESS);

    console.log(`👤 Wallet: ${wallet.address}`);
    console.log(`💰 Wallet Balance: ${ethers.formatUnits(walletBal, 18)} USDC`);
    console.log(`🏦 Contract Balance: ${ethers.formatUnits(contractBal, 18)} USDC\n`);

    if (walletBal === 0n) {
        console.log("❌ Wallet has no balance! Get testnet USDC from faucet.");
        return;
    }

    // Test with small amount
    const betId = Date.now();
    const amount = ethers.parseUnits("0.1", 18);

    console.log("📋 Transaction Parameters:");
    console.log(`   Bet ID: ${betId}`);
    console.log(`   Amount: ${ethers.formatUnits(amount, 18)} USDC`);
    console.log(`   Direction: 1 (UP)`);
    console.log(`   Duration: 10 seconds`);
    console.log(`   Entry Price: $100`);
    console.log(`   Market: 5 (SOL)\n`);

    try {
        // First, check if bet ID already exists
        console.log("🔍 Checking if bet ID exists...");
        const existingBet = await contract.bets(betId);

        if (existingBet.user !== ethers.ZeroAddress) {
            console.log(`❌ BET ID ${betId} ALREADY EXISTS!`);
            console.log(`   User: ${existingBet.user}`);
            console.log(`   Amount: ${ethers.formatUnits(existingBet.amount, 18)}`);
            console.log(`   Settled: ${existingBet.settled}\n`);
            console.log("💡 This is the problem! Using Date.now() causes ID collisions.");
            console.log("   Solution: Use a more unique ID or check if ID exists before using.\n");
            return;
        }

        console.log("✅ Bet ID is available\n");

        // Try to estimate gas
        console.log("⛽ Estimating gas...");
        const gasEstimate = await contract.placeBet.estimateGas(
            betId,
            1, // UP
            10, // 10 seconds
            BigInt(Math.floor(100 * 100000000)), // $100
            5, // SOL
            wallet.address,
            { value: amount }
        );

        console.log(`✅ Gas estimate: ${gasEstimate.toString()}\n`);

        // Send transaction
        console.log("📤 Sending transaction...");
        const tx = await contract.placeBet(
            betId,
            1,
            10,
            BigInt(Math.floor(100 * 100000000)),
            5,
            wallet.address,
            {
                value: amount,
                gasLimit: gasEstimate * 150n / 100n
            }
        );

        console.log(`✅ Transaction sent: ${tx.hash}`);
        console.log(`🔗 Explorer: https://testnet.arcscan.app/tx/${tx.hash}\n`);

        const receipt = await tx.wait();

        if (receipt.status === 1) {
            console.log("✅ TRANSACTION SUCCESSFUL!\n");
        } else {
            console.log("❌ Transaction failed\n");
        }

    } catch (error) {
        console.log("\n❌ ERROR CAUGHT:\n");
        console.log(`Message: ${error.message}\n`);

        if (error.reason) {
            console.log(`Reason: ${error.reason}\n`);
        }

        // Check for specific error patterns
        if (error.message.includes("Bet ID already exists")) {
            console.log("🔴 PROBLEM: Bet ID collision!");
            console.log("The bet ID generated by Date.now() is already in use.\n");
        }

        if (error.message.includes("nonce")) {
            console.log("🔴 PROBLEM: Nonce issue!");
        }

        if (error.message.includes("insufficient funds")) {
            console.log("🔴 PROBLEM: Insufficient funds in wallet!");
        }
    }
}

detailedTest();
