-- 005_trade_idempotency.sql
--
-- Makes the DATABASE the authority on "has this bet already been placed?"
--
-- Symptom this fixes: a user with ~52 USDC placed a 3.95 USDC trade and two
-- trade rows appeared at once - the real 3.95 bet and a phantom ~97 USDC one
-- that then sat in PENDING forever. The win card reported the 3.95 stake paying
-- ~97 USDC, and the balance grew by that inflated figure.
--
-- Root cause: `placeTrade` in nexus-core/src/classic.js only guarded
-- *concurrent* submits with a per-user in-process Set (`_tradeLocks`), which is
-- released the moment the first call returns. It never checked whether the
-- incoming bet id had already been placed. The bet id is generated by the
-- frontend, so a double-click, an aborted request retried, or a socket-driven
-- replay all produced a SECOND real on-chain placeBet and a second balance
-- deduction. Two independent defects then compounded:
--
--   1. The phantom bet was a real on-chain trade with a real stake, so it was
--      never garbage collected. Nothing settles a bet whose row the user cannot
--      see, so it stayed PENDING indefinitely.
--   2. `creditWinner` computed the payout as `amount / sharePrice` with no
--      ceiling. Near the 0.03 clamp floor a 3.95 USDC stake pays ~97 USDC,
--      which is 13x the 1.90x ceiling for a 15s trade. The phantom's inflated
--      payout is what the balance actually grew by.
--
-- Neither is fixable in application memory alone: `_tradeLocks` and
-- `cache.trades` are both in-process and are lost on restart, so the same
-- replay after a deploy re-opens the hole. This table makes the guard durable
-- and shared across instances.
--
-- Design mirrors credited_deposits (migration 004): the PRIMARY KEY *is* the
-- idempotency key, so the insert is the lock. Whoever inserts first owns the
-- placeBet; every replay gets Postgres 23505 and does nothing.
--
-- NOTE: the bet id is the idempotency key, not the tx hash. The tx hash does
-- not exist until after broadcast, so it cannot gate the broadcast. The bet id
-- is what the frontend already reuses across retries.

CREATE TABLE IF NOT EXISTS placed_bets (
    bet_id      TEXT PRIMARY KEY,                    -- the frontend-generated bet id; the idempotency key
    user_address TEXT NOT NULL,                      -- who placed it
    amount      NUMERIC(20, 6) NOT NULL DEFAULT 0,   -- stake requested
    symbol      TEXT,
    duration    INTEGER,
    status      TEXT,                                -- PENDING | WON | LOST | CANCELLED
    stake_tx_hash TEXT,                              -- filled in once broadcast succeeds
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),  -- first successful claim
    settled_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_placed_bets_user ON placed_bets(user_address);
CREATE INDEX IF NOT EXISTS idx_placed_bets_created ON placed_bets(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_placed_bets_stake_tx ON placed_bets(stake_tx_hash)
    WHERE stake_tx_hash IS NOT NULL;

-- Never let a malformed historical row abort the migration, and never let a
-- negative stake sit in the ledger.
ALTER TABLE placed_bets DROP CONSTRAINT IF EXISTS placed_bets_amount_nonneg;
ALTER TABLE placed_bets
    ADD CONSTRAINT placed_bets_amount_nonneg CHECK (amount >= 0);

-- Backfill from the trades table so a replay of a bet id that predates this
-- migration is still rejected. `on conflict do nothing` makes re-runs safe.
-- Only real user trades qualify: the trades table also holds funding rows
-- (status CONFIRMED, amount credited) and copy-trade bookkeeping, neither of
-- which is a bet id and neither of which should block a future bet.
--
-- Every source value is cast explicitly. The declared schema in 001/002 says
-- `duration integer`, but the live table turned out to hold it as TEXT, and a
-- plain `t.duration` aborted the whole insert with:
--
--   ERROR: 42804: column "duration" is of type integer but expression is of
--   type text
--
-- A single uncast column failed the entire migration, so nothing was applied and
-- trades stayed refused. Casting through text and only converting to int when
-- the value is genuinely numeric makes this work against either real schema, and
-- degrades a blank or malformed value to NULL rather than aborting the insert.
INSERT INTO placed_bets (bet_id, user_address, amount, symbol, duration, status, stake_tx_hash, created_at, settled_at)
SELECT DISTINCT ON (t.id::text)
       t.id::text,
       lower(t.user_address::text),
       COALESCE(t.amount::numeric, 0),
       t.symbol::text,
       CASE WHEN t.duration::text ~ '^[0-9]+$' THEN t.duration::text::int ELSE NULL END,
       t.status::text,
       t.tx_hash::text,
       to_timestamp(COALESCE(t.timestamp::text, '0')::double precision / 1000.0),
       CASE WHEN upper(t.status::text) IN ('WON','PAID','LOST','SETTLED')
            THEN to_timestamp(COALESCE(t.timestamp::text, '0')::double precision / 1000.0) END
FROM trades t
WHERE t.id IS NOT NULL
  AND t.id::text <> ''
  AND lower(t.user_address::text) IS NOT NULL
  AND upper(t.status::text) IN ('PENDING', 'RESOLVING', 'WON', 'PAID', 'LOST', 'SETTLED')
  AND t.symbol IS NOT NULL          -- funding rows have no symbol; they are not bets
ORDER BY t.id::text, COALESCE(t.timestamp::text, '0')::double precision DESC
ON CONFLICT (bet_id) DO NOTHING;
