console.error("\n\n====================================================================================");
console.error("🔴 STOP! You are attempting to run the OLD Arc Keeper.");
console.error("🟢 The production-ready Isolated Keeper is located in: /backend/arc-keeper");
console.error("");
console.error("👉 TO START THE CORRECT KEEPER:");
console.error("   cd backend/arc-keeper");
console.error("   npm run dev");
console.error("");
console.error("🚨 REASON FOR CHANGE:");
console.error("   1. Old keeper uses outdated scanning logic (Alchemys 10-block limit).");
console.error("   2. Old keeper lacks the isolated production architecture.");
console.error("   3. As per your request, the NEW keeper only listens to live events.");
console.error("====================================================================================\n\n");
process.exit(1);
